int screenWidth = 600;
int screenHeight = 800;
int originalApartmentScale = 100;
int minApartmentScale = 25;
int maxApartmentScale = 400;
int apartmentScale = originalApartmentScale;
int apartmentHeight = 5000;
int numApartments = apartmentHeight/originalApartmentScale;
int scrollSpeed = 20;
float zoomSpeed = 2;
int cameraY = screenHeight - apartmentHeight;
int cameraX = 100;
float cameraZoom = 0;
int keyPressDelay = 10;
int keyPressCounter;
int maxFloorPopulation = 5;
int maxCameraHeight = 0;
int minCameraHeight = 100000;
Floor [] apartments = new Floor[numApartments];
Elevator elevator1;
PImage[]upButton = new PImage[2];
int upNum = 0;
PImage[]downButton = new PImage[2];
int downNum = 0;
PImage[]leftButton = new PImage[2];
int leftNum = 0;
PImage[]rightButton = new PImage[2];
int rightNum = 0;
